# Form implementation generated from reading ui file 'testPyQtGraphInFigure.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import numpy as np


class Ui_Form(object):
    def setupUi(self, Form):
        self.n = 0
        Form.setObjectName("Form")
        Form.resize(1095, 669)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 610, 371, 41))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = PlotWidget(parent=Form)
        self.graphicsView.setGeometry(QtCore.QRect(20, 10, 1061, 581))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(560, 620, 461, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.btnClick)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Do the thing"))
        self.label.setText(_translate("Form", "Some text here i dunno"))

    def btnClick(self):
        #every time button is pressed change the data and change the figure
        self.n = self.n+1
        self.label.setText(str(self.n)) #update the label number

        x = np.random.normal(size=1000)
        self.graphicsView.plot(x)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
